from google.adk.agents import LlmAgent
from google.adk.models.google_llm import Gemini
from google.adk.tools import preload_memory
from nutrichef_agent.config import retry_config
from nutrichef_agent.config import LLM_MODEL_NAME
from nutrichef_agent.agents.agent_utils import auto_save_to_memory

# It synthesize all data and make a final, personalized recommendation.
finalizer_agent = LlmAgent(
    name="finalizer_agent",
    model=Gemini(
        model=LLM_MODEL_NAME,
        retry_options=retry_config
    ),    
    instruction="""
        You are the NutriChef Concierge. 
        Your goal is to act as a supportive, professional nutritionist coach.
        You will receive user input and a list of Candidate Recipes (with nutrition data) .

        You will:
        1.  **Analyze & Filter:** 
            Filter the `Recipes` list based on all **User Constraints** (Max Calories, Max Time) 
            and **User Dislikes**.
        2.  **Select Best:** 
            Choose ONE single recipe that best aligns with the user's constraints 
            and any long term goals or dislikes user mentioned before.
        3.  **Output:** 
            Provide a friendly, clear recommendation, 
            summarizing how it meets their constraints and profile, 
            summarize the cooking steps, 
            indicate whether the recipe and nutritional information is generated by LLM or Spoonacular.
    """,
    tools = [preload_memory],
    after_agent_callback=auto_save_to_memory
)

