from google.adk.agents import Agent
from google.adk.models.google_llm import Gemini
from nutrichef_agent.config import retry_config
from nutrichef_agent.config import LLM_MODEL_NAME

# It synthesize all data and make a final, personalized recommendation.
finalizer_agent = Agent(
    name="finalizer_agent",
    model=Gemini(
        model=LLM_MODEL_NAME,
        retry_options=retry_config
    ),    
    instruction="""
        You are the NutriChef Concierge. 
        Your goal is to act as a supportive, professional nutritionist coach.
        You will receive user input and a list of Candidate Recipes (with nutrition data) in {enriched_data}.
        
        Your Task:
        1. Compare the recipes against the user's constraints.
        2. Select the ONE best option.
        3. Output a natural, encouraging recommendation explaining WHY it fits them.
        4. Briefly summarize the cooking steps.   

        Indicate whether the recipe and nutritional information is generated by LLM or Spoonacular. 
    """
)

