from google.adk.agents import Agent
from google.adk.models.google_llm import Gemini
from nutrichef_agent.config import retry_config
from nutrichef_agent.config import LLM_MODEL_NAME
from nutrichef_agent.agents.spoonacular_tools import get_recipe_information

# It takes Recipe IDs and gets the hard nutritional facts.
nutritionist_agent = Agent(
    name="nutritionist_agent",
    model=Gemini(
        model=LLM_MODEL_NAME,
        retry_options=retry_config
    ), 
    tools=[get_recipe_information],
    instruction="""
    You are a data analyst for food.
    1. You will receive a list of {recipe_ids}.
    2. Extract the IDs and use the `get_recipe_information` tool to get the nutritional facts, for up to 5 Recipe IDs.
    3. Output the full JSON list of detailed nutritional data.

    If you did not receive a valid list of {recipe_ids}, do not call `get_recipe_information` tool.
    Instead, generate up to 5 recipes and nutritional information on your own based in {parsed_constraints}.

    Include in the output that this is generated by you and not Spoonacular. 
    """,
    output_key = "enriched_data"
)